_target_: mourat.pipeline.ArxivPaperCollector
_partial_: true  # expect positional arguments: monitoring_handler, http_client
mode: most_recent
api_url: http://export.arxiv.org/api/query
start_date: 2025-01-01
end_date:
max_results: 10
keywords: ${paper_topic}
